# CREATING ARRAYS

In [1]:
import numpy as np

In [ ]:
# One Dimensional Array

arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D) 
print(type(arr1D))  


In [2]:
# Two Dimensional Array

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Three Dimensional Array (Tensors)

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3D)


# Checking Array Properties

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
print(arr.shape)  
print(arr.size)   
print(arr.dtype)


2
(2, 3)
6
int64


# Special NumPy Arrays

In [6]:
# Creating Arrays with Default Values

zeros = np.zeros((3, 3))  # 3x3 matrix of zeros
ones = np.ones((2, 4))  # 2x4 matrix of ones
identity = np.identity(4)  # 4x4 identity matrix
constant = np.full((2, 3), 7)  # 2x3 matrix where all elements are 7
print(zeros, "\n")
print(ones, "\n")
print(identity , "\n")
print(constant, "\n")


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[7 7 7]
 [7 7 7]] 



In [7]:
#Creating Arrays with Random Numbers

random_uniform = np.random.rand(3, 3)  # Values between 0 and 1
random_normal = np.random.randn(3, 3)  # Normal distribution
random_ints = np.random.randint(10, 50, (3, 3))  # Integers between 10 and 50

print(random_uniform, "\n")
print(random_normal, "\n")
print(random_ints)


[[0.10371855 0.66823239 0.35966273]
 [0.35369785 0.44378943 0.84115176]
 [0.86894671 0.06588271 0.13090619]] 

[[-1.4858528  -1.1942079  -0.98271805]
 [ 0.37131984 -0.64401904 -0.81407508]
 [ 1.46465242  0.24732383 -0.09694007]] 

[[10 13 24]
 [31 38 26]
 [34 40 49]]


# INDEXING AND SLICING

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  # 30
print(arr[-1])  # 50


30
50


In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Elements 1 to 3 → [20 30 40]


[20 30 40]


In [10]:
arr2D = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr2D[1, 2])  # Element at row 1, col 2 → 60
print(arr2D[:, 1])  # Second column → [20 50 80]
print(arr2D[1:, 1:])  # Submatrix


60
[20 50 80]
[[50 60]
 [80 90]]


In [12]:
# reshaping an array
arr = np.arange(1, 13)  # [1 2 3 ... 12]
reshaped = arr.reshape(3, 4)  # 3x4 matrix
print(reshaped)

flat = reshaped.flatten()  # Converts back to 1D
print(flat)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# mathematical operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(a / 2)  # Divide by scalar


# matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)  # Matrix multiplication
print(dot_product)


## Statistical & Aggregate Functions

In [13]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))  # Mean
print(np.median(arr))  # Median
print(np.std(arr))  # Standard deviation
print(np.var(arr))  # Variance
print(np.sum(arr))  # Sum
print(np.min(arr))  # Minimum
print(np.max(arr))  # Maximum
print(np.argmin(arr))  # Index of minimum
print(np.argmax(arr))  # Index of maximum


30.0
30.0
14.142135623730951
200.0
150
10
50
0
4


## Boolean masking and Filtering 

In [15]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25  # Boolean mask (array of True/False values)
print(mask)  #(you can give an array as input to get the values of that indexes or True or False values)

print(arr[[1,2,4]]) # prints the values of the indexes given in the array
print(arr[mask])  # Filtered array: [30 40 50]


[False False  True  True  True]
[20 30 50]
[30 40 50]
